version: '3'

includes:
  build:
    taskfile: tasks/Taskfile_{{OS}}.yml
    flatten: true

# Cross-platform or meta tasks only

tasks:
  default:
    desc: Show available tasks
    cmds:
      - task --list-all

  test:
    desc: Run tests
    cmds:
      - go test ./...

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Vet Go code
    cmds:
      - go vet ./...

  deps:
    desc: Download and tidy dependencies
    cmds:
      - go mod download
      - go mod tidy

  dev:
    desc: Development workflow - build, test, and run
    deps: [deps, fmt, vet, test, build]
    cmds:
      - echo "Development workflow complete"
      - echo "Run 'task windows:run' to start the application" 